[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && cd ../client && npm install && npm run build"

[deploy]
startCommand = "cd server && node index.js"
restartPolicyType = "on_failure"
